version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
  database:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/1-dump.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: qwerty
      MYSQL_USER: qwerty
      MYSQL_PASSWORD: qwerty

volumes:
  mysql:
