import { servicePlayers } from './services/servicePlayers';
import { controllerPlayers } from './controller/controllerPlayers';
import { viewPlayers } from './view/viewPlayers';
import { FetchService } from './services/fetch.service';
import { formService } from './services/form.service';
import { DexieService } from './services/storage.service';
const fetch = new FetchService();
const view = new viewPlayers();
const dexie = new DexieService();
const service = new servicePlayers(fetch, dexie);
const validateService = new formService();
const controller = new controllerPlayers(view, service, validateService);
